import Restaurant from "../types/Restaurant";
import DayOfWeek from "../enums/DayOfWeek";

const { TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY } = DayOfWeek;

const PilotRestaurant: Restaurant = {
  id: "r-pilot",
  address: "800 Brazos St., Austin, Texas, 78701",
  adminIds: [],
  name: "Loman's Pizza",
  bannerURL: "https://api.dicebear.com/9.x/glass/svg",
  //Dimensions of Moontower Cider dining room
  dimensions: { x: 25, y: 30 },
  menuItemIds: [
    "i-pilot-appetizer-1",
    "i-pilot-appetizer-2",
    "i-pilot-appetizer-3",
    "i-pilot-appetizer-4",
    "i-pilot-appetizer-5",
    "i-pilot-appetizer-6",
    "i-pilot-appetizer-7",
    "i-pilot-side-1",
    "i-pilot-side-2",
    "i-pilot-side-3",
    "i-pilot-side-4",
    "i-pilot-side-5",
    "i-pilot-drink-1",
    "i-pilot-drink-2",
    "i-pilot-drink-3",
    "i-pilot-drink-4",
    "i-pilot-dessert-1",
    "i-pilot-dessert-2",
    "i-pilot-entree-1",
    "i-pilot-entree-2",
    "i-pilot-entree-3",
    "i-pilot-entree-4",
    "i-pilot-entree-5",
    "i-pilot-entree-6",
    "i-pilot-entree-7",
    "i-pilot-entree-8",
    "i-pilot-entree-9",
    "i-pilot-entree-10",
    "i-pilot-entree-11",
    "i-pilot-entree-12",
    "i-pilot-entree-13",
    "i-pilot-entree-14",
    "i-pilot-entree-15",
    "i-pilot-entree-16",
    "i-pilot-entree-17",
    "i-pilot-entree-18",
    "i-pilot-entree-19",
    "i-pilot-entree-20",
    "i-pilot-entree-21",
    "i-pilot-entree-22",
  ],
  outOfStockItemIds: [],
  tableIds: [
    "t-pilot-4-A",
    "t-pilot-4-B",
    "t-pilot-4-C",
    "t-pilot-4-D",
    "t-pilot-6-A",
    "t-pilot-6-B",
    "t-pilot-8-A",
    "t-pilot-8-B",
  ],
  reservationIds: [],
  defaultOperationHours: [
    {
      startTime: "09:00",
      endTime: "23:00",
      repeat: [TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY],
    },
  ],
  defaultHoldMinutes: 5,
  defaultReservationLength: 90,
};

export default PilotRestaurant;
