/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIdineRouteImport } from './routes/dashboard/_idine'
import { Route as DashboardIdineIndexRouteImport } from './routes/dashboard/_idine.index'
import { Route as RestaurantsLomansPizzaLayoutRouteImport } from './routes/restaurants/lomans-pizza/_layout'
import { Route as DashboardIdineAdminRouteImport } from './routes/dashboard/_idine.admin'
import { Route as RestaurantsLomansPizzaLayoutIndexRouteImport } from './routes/restaurants/lomans-pizza/_layout.index'
import { Route as UpdateNumberNamePhoneRouteImport } from './routes/update/$number.$name.$phone'
import { Route as RestaurantsLomansPizzaLayoutTosRouteImport } from './routes/restaurants/lomans-pizza/_layout.tos'
import { Route as RestaurantsLomansPizzaLayoutMenuRouteImport } from './routes/restaurants/lomans-pizza/_layout.menu'
import { Route as DashboardIdineEditNumberRouteImport } from './routes/dashboard/_idine.edit.$number'
import { Route as ConfirmationNumberNamePhoneRouteImport } from './routes/confirmation/$number.$name.$phone'

const DashboardRouteImport = createFileRoute('/dashboard')()
const RestaurantsLomansPizzaRouteImport = createFileRoute(
  '/restaurants/lomans-pizza',
)()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsLomansPizzaRoute = RestaurantsLomansPizzaRouteImport.update({
  id: '/restaurants/lomans-pizza',
  path: '/restaurants/lomans-pizza',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdineRoute = DashboardIdineRouteImport.update({
  id: '/_idine',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIdineIndexRoute = DashboardIdineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardIdineRoute,
} as any)
const RestaurantsLomansPizzaLayoutRoute =
  RestaurantsLomansPizzaLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => RestaurantsLomansPizzaRoute,
  } as any)
const DashboardIdineAdminRoute = DashboardIdineAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardIdineRoute,
} as any)
const RestaurantsLomansPizzaLayoutIndexRoute =
  RestaurantsLomansPizzaLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RestaurantsLomansPizzaLayoutRoute,
  } as any)
const UpdateNumberNamePhoneRoute = UpdateNumberNamePhoneRouteImport.update({
  id: '/update/$number/$name/$phone',
  path: '/update/$number/$name/$phone',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsLomansPizzaLayoutTosRoute =
  RestaurantsLomansPizzaLayoutTosRouteImport.update({
    id: '/tos',
    path: '/tos',
    getParentRoute: () => RestaurantsLomansPizzaLayoutRoute,
  } as any)
const RestaurantsLomansPizzaLayoutMenuRoute =
  RestaurantsLomansPizzaLayoutMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => RestaurantsLomansPizzaLayoutRoute,
  } as any)
const DashboardIdineEditNumberRoute =
  DashboardIdineEditNumberRouteImport.update({
    id: '/edit/$number',
    path: '/edit/$number',
    getParentRoute: () => DashboardIdineRoute,
  } as any)
const ConfirmationNumberNamePhoneRoute =
  ConfirmationNumberNamePhoneRouteImport.update({
    id: '/confirmation/$number/$name/$phone',
    path: '/confirmation/$number/$name/$phone',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIdineRouteWithChildren
  '/dashboard/admin': typeof DashboardIdineAdminRoute
  '/restaurants/lomans-pizza': typeof RestaurantsLomansPizzaLayoutRouteWithChildren
  '/dashboard/': typeof DashboardIdineIndexRoute
  '/confirmation/$number/$name/$phone': typeof ConfirmationNumberNamePhoneRoute
  '/dashboard/edit/$number': typeof DashboardIdineEditNumberRoute
  '/restaurants/lomans-pizza/menu': typeof RestaurantsLomansPizzaLayoutMenuRoute
  '/restaurants/lomans-pizza/tos': typeof RestaurantsLomansPizzaLayoutTosRoute
  '/update/$number/$name/$phone': typeof UpdateNumberNamePhoneRoute
  '/restaurants/lomans-pizza/': typeof RestaurantsLomansPizzaLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIdineIndexRoute
  '/dashboard/admin': typeof DashboardIdineAdminRoute
  '/restaurants/lomans-pizza': typeof RestaurantsLomansPizzaLayoutIndexRoute
  '/confirmation/$number/$name/$phone': typeof ConfirmationNumberNamePhoneRoute
  '/dashboard/edit/$number': typeof DashboardIdineEditNumberRoute
  '/restaurants/lomans-pizza/menu': typeof RestaurantsLomansPizzaLayoutMenuRoute
  '/restaurants/lomans-pizza/tos': typeof RestaurantsLomansPizzaLayoutTosRoute
  '/update/$number/$name/$phone': typeof UpdateNumberNamePhoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_idine': typeof DashboardIdineRouteWithChildren
  '/dashboard/_idine/admin': typeof DashboardIdineAdminRoute
  '/restaurants/lomans-pizza': typeof RestaurantsLomansPizzaRouteWithChildren
  '/restaurants/lomans-pizza/_layout': typeof RestaurantsLomansPizzaLayoutRouteWithChildren
  '/dashboard/_idine/': typeof DashboardIdineIndexRoute
  '/confirmation/$number/$name/$phone': typeof ConfirmationNumberNamePhoneRoute
  '/dashboard/_idine/edit/$number': typeof DashboardIdineEditNumberRoute
  '/restaurants/lomans-pizza/_layout/menu': typeof RestaurantsLomansPizzaLayoutMenuRoute
  '/restaurants/lomans-pizza/_layout/tos': typeof RestaurantsLomansPizzaLayoutTosRoute
  '/update/$number/$name/$phone': typeof UpdateNumberNamePhoneRoute
  '/restaurants/lomans-pizza/_layout/': typeof RestaurantsLomansPizzaLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/restaurants/lomans-pizza'
    | '/dashboard/'
    | '/confirmation/$number/$name/$phone'
    | '/dashboard/edit/$number'
    | '/restaurants/lomans-pizza/menu'
    | '/restaurants/lomans-pizza/tos'
    | '/update/$number/$name/$phone'
    | '/restaurants/lomans-pizza/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/restaurants/lomans-pizza'
    | '/confirmation/$number/$name/$phone'
    | '/dashboard/edit/$number'
    | '/restaurants/lomans-pizza/menu'
    | '/restaurants/lomans-pizza/tos'
    | '/update/$number/$name/$phone'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/_idine'
    | '/dashboard/_idine/admin'
    | '/restaurants/lomans-pizza'
    | '/restaurants/lomans-pizza/_layout'
    | '/dashboard/_idine/'
    | '/confirmation/$number/$name/$phone'
    | '/dashboard/_idine/edit/$number'
    | '/restaurants/lomans-pizza/_layout/menu'
    | '/restaurants/lomans-pizza/_layout/tos'
    | '/update/$number/$name/$phone'
    | '/restaurants/lomans-pizza/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RestaurantsLomansPizzaRoute: typeof RestaurantsLomansPizzaRouteWithChildren
  ConfirmationNumberNamePhoneRoute: typeof ConfirmationNumberNamePhoneRoute
  UpdateNumberNamePhoneRoute: typeof UpdateNumberNamePhoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/lomans-pizza': {
      id: '/restaurants/lomans-pizza'
      path: '/restaurants/lomans-pizza'
      fullPath: '/restaurants/lomans-pizza'
      preLoaderRoute: typeof RestaurantsLomansPizzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_idine': {
      id: '/dashboard/_idine'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIdineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_idine/': {
      id: '/dashboard/_idine/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIdineIndexRouteImport
      parentRoute: typeof DashboardIdineRoute
    }
    '/restaurants/lomans-pizza/_layout': {
      id: '/restaurants/lomans-pizza/_layout'
      path: '/restaurants/lomans-pizza'
      fullPath: '/restaurants/lomans-pizza'
      preLoaderRoute: typeof RestaurantsLomansPizzaLayoutRouteImport
      parentRoute: typeof RestaurantsLomansPizzaRoute
    }
    '/dashboard/_idine/admin': {
      id: '/dashboard/_idine/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardIdineAdminRouteImport
      parentRoute: typeof DashboardIdineRoute
    }
    '/restaurants/lomans-pizza/_layout/': {
      id: '/restaurants/lomans-pizza/_layout/'
      path: '/'
      fullPath: '/restaurants/lomans-pizza/'
      preLoaderRoute: typeof RestaurantsLomansPizzaLayoutIndexRouteImport
      parentRoute: typeof RestaurantsLomansPizzaLayoutRoute
    }
    '/update/$number/$name/$phone': {
      id: '/update/$number/$name/$phone'
      path: '/update/$number/$name/$phone'
      fullPath: '/update/$number/$name/$phone'
      preLoaderRoute: typeof UpdateNumberNamePhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/lomans-pizza/_layout/tos': {
      id: '/restaurants/lomans-pizza/_layout/tos'
      path: '/tos'
      fullPath: '/restaurants/lomans-pizza/tos'
      preLoaderRoute: typeof RestaurantsLomansPizzaLayoutTosRouteImport
      parentRoute: typeof RestaurantsLomansPizzaLayoutRoute
    }
    '/restaurants/lomans-pizza/_layout/menu': {
      id: '/restaurants/lomans-pizza/_layout/menu'
      path: '/menu'
      fullPath: '/restaurants/lomans-pizza/menu'
      preLoaderRoute: typeof RestaurantsLomansPizzaLayoutMenuRouteImport
      parentRoute: typeof RestaurantsLomansPizzaLayoutRoute
    }
    '/dashboard/_idine/edit/$number': {
      id: '/dashboard/_idine/edit/$number'
      path: '/edit/$number'
      fullPath: '/dashboard/edit/$number'
      preLoaderRoute: typeof DashboardIdineEditNumberRouteImport
      parentRoute: typeof DashboardIdineRoute
    }
    '/confirmation/$number/$name/$phone': {
      id: '/confirmation/$number/$name/$phone'
      path: '/confirmation/$number/$name/$phone'
      fullPath: '/confirmation/$number/$name/$phone'
      preLoaderRoute: typeof ConfirmationNumberNamePhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardIdineRouteChildren {
  DashboardIdineAdminRoute: typeof DashboardIdineAdminRoute
  DashboardIdineIndexRoute: typeof DashboardIdineIndexRoute
  DashboardIdineEditNumberRoute: typeof DashboardIdineEditNumberRoute
}

const DashboardIdineRouteChildren: DashboardIdineRouteChildren = {
  DashboardIdineAdminRoute: DashboardIdineAdminRoute,
  DashboardIdineIndexRoute: DashboardIdineIndexRoute,
  DashboardIdineEditNumberRoute: DashboardIdineEditNumberRoute,
}

const DashboardIdineRouteWithChildren = DashboardIdineRoute._addFileChildren(
  DashboardIdineRouteChildren,
)

interface DashboardRouteChildren {
  DashboardIdineRoute: typeof DashboardIdineRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIdineRoute: DashboardIdineRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface RestaurantsLomansPizzaLayoutRouteChildren {
  RestaurantsLomansPizzaLayoutMenuRoute: typeof RestaurantsLomansPizzaLayoutMenuRoute
  RestaurantsLomansPizzaLayoutTosRoute: typeof RestaurantsLomansPizzaLayoutTosRoute
  RestaurantsLomansPizzaLayoutIndexRoute: typeof RestaurantsLomansPizzaLayoutIndexRoute
}

const RestaurantsLomansPizzaLayoutRouteChildren: RestaurantsLomansPizzaLayoutRouteChildren =
  {
    RestaurantsLomansPizzaLayoutMenuRoute:
      RestaurantsLomansPizzaLayoutMenuRoute,
    RestaurantsLomansPizzaLayoutTosRoute: RestaurantsLomansPizzaLayoutTosRoute,
    RestaurantsLomansPizzaLayoutIndexRoute:
      RestaurantsLomansPizzaLayoutIndexRoute,
  }

const RestaurantsLomansPizzaLayoutRouteWithChildren =
  RestaurantsLomansPizzaLayoutRoute._addFileChildren(
    RestaurantsLomansPizzaLayoutRouteChildren,
  )

interface RestaurantsLomansPizzaRouteChildren {
  RestaurantsLomansPizzaLayoutRoute: typeof RestaurantsLomansPizzaLayoutRouteWithChildren
}

const RestaurantsLomansPizzaRouteChildren: RestaurantsLomansPizzaRouteChildren =
  {
    RestaurantsLomansPizzaLayoutRoute:
      RestaurantsLomansPizzaLayoutRouteWithChildren,
  }

const RestaurantsLomansPizzaRouteWithChildren =
  RestaurantsLomansPizzaRoute._addFileChildren(
    RestaurantsLomansPizzaRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RestaurantsLomansPizzaRoute: RestaurantsLomansPizzaRouteWithChildren,
  ConfirmationNumberNamePhoneRoute: ConfirmationNumberNamePhoneRoute,
  UpdateNumberNamePhoneRoute: UpdateNumberNamePhoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
