/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsLomansPizzaLayoutRouteImport } from './routes/restaurants/lomans-pizza/_layout'
import { Route as RestaurantsLomansPizzaLayoutIndexRouteImport } from './routes/restaurants/lomans-pizza/_layout.index'
import { Route as RestaurantsLomansPizzaLayoutTosRouteImport } from './routes/restaurants/lomans-pizza/_layout.tos'
import { Route as RestaurantsLomansPizzaLayoutMenuRouteImport } from './routes/restaurants/lomans-pizza/_layout.menu'

const RestaurantsLomansPizzaRouteImport = createFileRoute(
  '/restaurants/lomans-pizza',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsLomansPizzaRoute = RestaurantsLomansPizzaRouteImport.update({
  id: '/restaurants/lomans-pizza',
  path: '/restaurants/lomans-pizza',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsLomansPizzaLayoutRoute =
  RestaurantsLomansPizzaLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => RestaurantsLomansPizzaRoute,
  } as any)
const RestaurantsLomansPizzaLayoutIndexRoute =
  RestaurantsLomansPizzaLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RestaurantsLomansPizzaLayoutRoute,
  } as any)
const RestaurantsLomansPizzaLayoutTosRoute =
  RestaurantsLomansPizzaLayoutTosRouteImport.update({
    id: '/tos',
    path: '/tos',
    getParentRoute: () => RestaurantsLomansPizzaLayoutRoute,
  } as any)
const RestaurantsLomansPizzaLayoutMenuRoute =
  RestaurantsLomansPizzaLayoutMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => RestaurantsLomansPizzaLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/restaurants/lomans-pizza': typeof RestaurantsLomansPizzaLayoutRouteWithChildren
  '/restaurants/lomans-pizza/menu': typeof RestaurantsLomansPizzaLayoutMenuRoute
  '/restaurants/lomans-pizza/tos': typeof RestaurantsLomansPizzaLayoutTosRoute
  '/restaurants/lomans-pizza/': typeof RestaurantsLomansPizzaLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/restaurants/lomans-pizza': typeof RestaurantsLomansPizzaLayoutIndexRoute
  '/restaurants/lomans-pizza/menu': typeof RestaurantsLomansPizzaLayoutMenuRoute
  '/restaurants/lomans-pizza/tos': typeof RestaurantsLomansPizzaLayoutTosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/restaurants/lomans-pizza': typeof RestaurantsLomansPizzaRouteWithChildren
  '/restaurants/lomans-pizza/_layout': typeof RestaurantsLomansPizzaLayoutRouteWithChildren
  '/restaurants/lomans-pizza/_layout/menu': typeof RestaurantsLomansPizzaLayoutMenuRoute
  '/restaurants/lomans-pizza/_layout/tos': typeof RestaurantsLomansPizzaLayoutTosRoute
  '/restaurants/lomans-pizza/_layout/': typeof RestaurantsLomansPizzaLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/restaurants/lomans-pizza'
    | '/restaurants/lomans-pizza/menu'
    | '/restaurants/lomans-pizza/tos'
    | '/restaurants/lomans-pizza/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/restaurants/lomans-pizza'
    | '/restaurants/lomans-pizza/menu'
    | '/restaurants/lomans-pizza/tos'
  id:
    | '__root__'
    | '/'
    | '/restaurants/lomans-pizza'
    | '/restaurants/lomans-pizza/_layout'
    | '/restaurants/lomans-pizza/_layout/menu'
    | '/restaurants/lomans-pizza/_layout/tos'
    | '/restaurants/lomans-pizza/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestaurantsLomansPizzaRoute: typeof RestaurantsLomansPizzaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/lomans-pizza': {
      id: '/restaurants/lomans-pizza'
      path: '/restaurants/lomans-pizza'
      fullPath: '/restaurants/lomans-pizza'
      preLoaderRoute: typeof RestaurantsLomansPizzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/lomans-pizza/_layout': {
      id: '/restaurants/lomans-pizza/_layout'
      path: '/restaurants/lomans-pizza'
      fullPath: '/restaurants/lomans-pizza'
      preLoaderRoute: typeof RestaurantsLomansPizzaLayoutRouteImport
      parentRoute: typeof RestaurantsLomansPizzaRoute
    }
    '/restaurants/lomans-pizza/_layout/': {
      id: '/restaurants/lomans-pizza/_layout/'
      path: '/'
      fullPath: '/restaurants/lomans-pizza/'
      preLoaderRoute: typeof RestaurantsLomansPizzaLayoutIndexRouteImport
      parentRoute: typeof RestaurantsLomansPizzaLayoutRoute
    }
    '/restaurants/lomans-pizza/_layout/tos': {
      id: '/restaurants/lomans-pizza/_layout/tos'
      path: '/tos'
      fullPath: '/restaurants/lomans-pizza/tos'
      preLoaderRoute: typeof RestaurantsLomansPizzaLayoutTosRouteImport
      parentRoute: typeof RestaurantsLomansPizzaLayoutRoute
    }
    '/restaurants/lomans-pizza/_layout/menu': {
      id: '/restaurants/lomans-pizza/_layout/menu'
      path: '/menu'
      fullPath: '/restaurants/lomans-pizza/menu'
      preLoaderRoute: typeof RestaurantsLomansPizzaLayoutMenuRouteImport
      parentRoute: typeof RestaurantsLomansPizzaLayoutRoute
    }
  }
}

interface RestaurantsLomansPizzaLayoutRouteChildren {
  RestaurantsLomansPizzaLayoutMenuRoute: typeof RestaurantsLomansPizzaLayoutMenuRoute
  RestaurantsLomansPizzaLayoutTosRoute: typeof RestaurantsLomansPizzaLayoutTosRoute
  RestaurantsLomansPizzaLayoutIndexRoute: typeof RestaurantsLomansPizzaLayoutIndexRoute
}

const RestaurantsLomansPizzaLayoutRouteChildren: RestaurantsLomansPizzaLayoutRouteChildren =
  {
    RestaurantsLomansPizzaLayoutMenuRoute:
      RestaurantsLomansPizzaLayoutMenuRoute,
    RestaurantsLomansPizzaLayoutTosRoute: RestaurantsLomansPizzaLayoutTosRoute,
    RestaurantsLomansPizzaLayoutIndexRoute:
      RestaurantsLomansPizzaLayoutIndexRoute,
  }

const RestaurantsLomansPizzaLayoutRouteWithChildren =
  RestaurantsLomansPizzaLayoutRoute._addFileChildren(
    RestaurantsLomansPizzaLayoutRouteChildren,
  )

interface RestaurantsLomansPizzaRouteChildren {
  RestaurantsLomansPizzaLayoutRoute: typeof RestaurantsLomansPizzaLayoutRouteWithChildren
}

const RestaurantsLomansPizzaRouteChildren: RestaurantsLomansPizzaRouteChildren =
  {
    RestaurantsLomansPizzaLayoutRoute:
      RestaurantsLomansPizzaLayoutRouteWithChildren,
  }

const RestaurantsLomansPizzaRouteWithChildren =
  RestaurantsLomansPizzaRoute._addFileChildren(
    RestaurantsLomansPizzaRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestaurantsLomansPizzaRoute: RestaurantsLomansPizzaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
